{{ if .Values.selfsigned.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubernetes-ca-issuer
spec:
  ca:
    secretName: kubernetes-ca
---
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          ttl 30
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    {{ .Values.selfsigned.cluster_domain }}:53 {
    hosts {
        {{ .Values.selfsigned.coredns_ip }} iam.{{ .Values.selfsigned.cluster_domain }}
        {{ .Values.selfsigned.coredns_ip }} registry.{{ .Values.selfsigned.cluster_domain }}
        {{ .Values.selfsigned.coredns_ip }} mgmt.{{ .Values.selfsigned.cluster_domain }}
        {{ .Values.selfsigned.coredns_ip }} argocd.{{ .Values.selfsigned.cluster_domain }}
        {{ .Values.selfsigned.coredns_ip }} kubeflow.{{ .Values.selfsigned.cluster_domain }}
        fallthrough
      }
    forward . /etc/resolv.conf
    cache 30
    }
kind: ConfigMap
metadata:
  labels:
    k0s.k0sproject.io/stack: coredns
  name: coredns
  namespace: kube-system
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: wildcard-domain-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-domain-tls
  namespace: traefik
spec:
  secretName: wildcard-domain-tls
  dnsNames:
    - "{{ .Values.selfsigned.cluster_domain }}"
    - "*.{{ .Values.selfsigned.cluster_domain }}"
  issuerRef:
    name: kubernetes-ca-issuer
    kind: ClusterIssuer
{{ end }}