#SPDX-License-Identifier: MIT-0
---
# defaults file for configure_oidc_authentication

# Path to the configuration folder containing env.json and cluster config YAML
config_folder: /opt/maia/config
configure_rancher: true
configure_harbor: true

harbor_admin_user: admin
harbor_admin_pass: Harbor12345
