{{- if .Values.maia_workspace_base_values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-maia-workspace-base
  namespace: {{ .Values.argo_namespace }}
spec:
  project: {{ .Release.Name }}
  source:
    chart: {{ .Values.maia_workspace_base_values.chart_name }}
    repoURL: {{ .Values.maia_workspace_base_values.repo_url }}
    targetRevision: {{ .Values.maia_workspace_base_values.chart_version }}
    helm:
      releaseName: {{ .Release.Name }}-maia-workspace-base
      valuesObject:
      {{ .Values.maia_workspace_base_values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.destination_server }}
    namespace: {{ .Values.namespace }}
{{- end }}