{{- if .Values.maia_gpu_booking_pod_terminator_values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-maia-gpu-booking-pod-terminator
  namespace: {{ .Values.argo_namespace }}
spec:
  project: {{ .Release.Name }}
  source:
    {{- if .Values.maia_gpu_booking_pod_terminator_values.chart_name }}
    chart: {{ .Values.maia_gpu_booking_pod_terminator_values.chart_name }}
    {{- end }}
    {{- if .Values.maia_gpu_booking_pod_terminator_values.path }}
    path: {{ .Values.maia_gpu_booking_pod_terminator_values.path }}
    {{- end }}
    repoURL: {{ .Values.maia_gpu_booking_pod_terminator_values.repo_url }}
    targetRevision: {{ .Values.maia_gpu_booking_pod_terminator_values.chart_version }}
    helm:
      releaseName: {{ .Release.Name }}-maia-gpu-booking-pod-terminator
      valuesObject:
      {{ .Values.maia_gpu_booking_pod_terminator_values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.destination_server }}
    namespace: {{ .Values.namespace }}
{{- end }}