#SPDX-License-Identifier: MIT-0
---
# tasks file for nfs
- name: Include server tasks
  ansible.builtin.include_tasks: server.yml
  when: "'nfs_server' in group_names"

- name: Include client tasks
  ansible.builtin.include_tasks: client.yml
  when: "'nfs_clients' in group_names"
