{{- if .Values.gpu_booking_values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-gpu-booking
  namespace: {{ .Values.argo_namespace }}
spec:
  project: {{ .Release.Name }}
  source:
    {{- if .Values.gpu_booking_values.chart_name }}
    chart: {{ .Values.gpu_booking_values.chart_name }}
    {{- end }}
    {{- if .Values.gpu_booking_values.path }}
    path: {{ .Values.gpu_booking_values.path }}
    {{- end }}
    repoURL: {{ .Values.gpu_booking_values.repo_url }}
    targetRevision: {{ .Values.gpu_booking_values.chart_version }}
    helm:
      releaseName: {{ .Release.Name }}-gpu-booking
      valuesObject:
      {{ .Values.gpu_booking_values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.destination_server }}
    namespace: {{ .Values.gpu_booking_values.namespace }}
{{- end }}