{{- if .Values.metrics_server_values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-metrics-server
  namespace: {{ .Values.argo_namespace }}
spec:
  project: {{ .Release.Name }}
  source:
    chart: {{ .Values.metrics_server_values.chart_name }}
    repoURL: {{ .Values.metrics_server_values.repo_url }}
    targetRevision: {{ .Values.metrics_server_values.chart_version }}
    helm:
      releaseName: {{ .Release.Name }}-metrics-server
      valuesObject:
      {{ .Values.metrics_server_values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.destination_server }}
    namespace: {{ .Values.metrics_server_values.namespace }}
{{- end }}