{{- range .Values.users }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: claim-{{ .jupyterhub_username }}
    namespace: {{ $.Values.namespace }}
spec:
  storageClassName: {{ $.Values.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

{{- end }}