#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Simone Bendazzoli <simben@kth.se>
  description: Configure LVM (Logical Volume Manager) for MAIA storage, creating volume groups and logical volumes for local and NFS storage.
  company: MAIA Project

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-3.0-only

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: [lvm, storage, volume, filesystem]
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.


argument_specs:
  main:
    description: Configure LVM (Logical Volume Manager) for MAIA storage, creating volume groups and logical volumes for local and NFS storage.
    short_description: Configure LVM (Logical Volume Manager) for MAIA storage
    options:
        device_list:
          type: list
          required: true
          elements: str
          description: "List of physical volumes (devices) to use for the volume group (required)"
        local_storage_size:
          type: str
          required: false
          default: 100%FREE
          description: "Size of the local storage logical volume, can be size like '300g' or percentage like '100%FREE' (optional)"
        nfs_storage_size:
          type: str
          required: false
          default: 100%FREE
          description: "Size of the NFS storage logical volume, can be size like '1.8t' or percentage like '100%FREE'. Only used when host is in nfs_server group (optional)"
