apiVersion: v1
kind: Service
metadata:
  name: {{ include "maia-gpu-workspace.fullname" . }}
  labels:
    {{- include "maia-gpu-workspace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "maia-gpu-workspace.selectorLabels" . | nindent 4 }}
