#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Simone Bendazzoli <simben@kth.se>
  description: Install and configure CIFS (Common Internet File System) support for Kubernetes. Sets up the CIFS volume plugin that allows Kubernetes to mount CIFS shares as persistent volumes.
  company: MAIA Project

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-3.0-only

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: [cifs, storage, kubernetes, volume, plugin]
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.


argument_specs:
  main:
    options:
        config_folder:
          type: str
          required: true
          description: "Path to the configuration folder containing the CIFS private key (required)"
        cifs_private_key_name:
          type: str
          required: false
          default: cifs_key
          description: "Name of the private key file in the config folder (optional)"
        volume_driver_path:
          type: str
          required: false
          default: /var/lib/kubelet/volumeplugins/fstab~cifs
          description: "Path to the volume driver plugin directory (optional)"
        cifs_script_url:
          type: str
          required: false
          default: https://raw.githubusercontent.com/minnelab/maia/master/CIFS/cifs
          description: "URL for the CIFS plugin script (optional)"
        cifs_decrypt_script_url:
          type: str
          required: false
          default: https://raw.githubusercontent.com/minnelab/maia/master/CIFS/decrypt_string.py
          description: "URL for the decrypt_string.py script (optional)"
