{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
  name: {{ include "hive.fullname" $ }}{{"-ingress"}}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - pathType: Prefix
            path: /{{ .Values.ingress.path}}
            backend:
              service:
                name: {{ include "hive.fullname" . }}
                port:
                  number: {{ .Values.ingress.port | int }}
  tls:
    - hosts:
        - {{ .Values.ingress.host}}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
  
  {{- end }}