name: Publish Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  build-test-pypi:
    name: Build, Test and publish Python ðŸ distributions ðŸ“¦ to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install setuptools
        run: |
          python -m pip install --user --upgrade setuptools wheel
      - name: Build and test source archive and wheel file
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          root_dir=$PWD
          echo "$root_dir"
          set -e
          python -m pip install numpy
          python -m pip install -r requirements.txt
          
          # build tar.gz and wheel
          python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
          tmp_dir=$(mktemp -d)
          cp dist/maia_toolkit* "$tmp_dir"
          cd "$tmp_dir"
          ls -al
          
          
          # install from tar.gz
          python -m pip install maia_toolkit*.tar.gz
          # python -c 'import MAIA; print(MAIA.__version__) ' 2>&1 | grep -iv "unknown"
          # python -c 'import MAIA; print(MAIA.__file__)'
          python -m pip uninstall -y maia-toolkit
          rm maia_toolkit*.tar.gz
          
          # install from wheel
          python -m pip install maia_toolkit*.whl
          # python -c 'import MAIA; print(MAIA.__version__) ' 2>&1 | grep -iv "unknown"
          # python -c 'import MAIA; print(MAIA.__file__)'
          
          # clean up
          cd "$root_dir"
          rm -r "$tmp_dir"
          rm -rf MAIA/
          ls -al .
      - name: Quick test installed
        run: |
          python -m pip install -r requirements.txt
                # python -m tests.min_tests
        env:
          QUICKTEST: True

      - if: startsWith(github.ref, 'refs/tags/')
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - if: startsWith(github.ref, 'refs/tags/')
        name: Check artifacts
        run: |
          ls -al dist/
          rm dist/maia_toolkit*.tar.gz
          ls -al dist/

      - if: startsWith(github.ref, 'refs/tags/')
        name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true
      
      - name: Inject version into install_MAIA.sh
        run: |
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"
          sed -i "s/VERSION=.*/VERSION=${VERSION}/" install_MAIA.sh
          MAIA_INSTALLATION_VERSION=$(git ls-remote --tags https://github.com/minnelab/MAIA.git \
                                    | awk '{print $2}' \
                                    | sed 's|refs/tags/||' \
                                    | grep '^ansible-maia.installation-v' \
                                    | sort -V \
                                    | tail -n 1 \
                                    | sed 's/\^{}$//' \
                                    | sed 's/^ansible-maia.installation-v//')
          sed -i "s/MAIA_INSTALLATION_VERSION=.*/MAIA_INSTALLATION_VERSION=${MAIA_INSTALLATION_VERSION}/" install_MAIA.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: True
          files: |
            install_MAIA.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-pypi:
    name: Publish Python ðŸ distributions ðŸ“¦ to PyPI
    needs: build-test-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a Source
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Extract tag name
        id: tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Trigger Read the Docs build for tag
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://readthedocs.org/api/v3/projects/maia-toolkit/versions/${{ steps.tag.outputs.tag }}/builds/

      - name: Trigger Read the Docs to make the documentation available
        run: |
          curl -X PATCH -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://readthedocs.org/api/v3/projects/maia-toolkit/versions/${{ steps.tag.outputs.tag }}/ -d '{"active": true}'